[build]
  # This is a static site, so no build command is needed.
  command = ""
  # The publish directory is the root of the project.
  publish = "." 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
